version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: bankappdb
      MYSQL_ROOT_PASSWORD: Test@123
    ports:
      - "3306:3306"
    networks:
      - bank-net

  bankapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8000:8080"
    networks:
      - bank-net

networks:
  bank-net:
    driver: bridge
